window.languageObj = {
    "zh": {
        "name": "马聆风",
        "nickname": "Jerry Ma",
        "university1": "华中科技大学 计算机科学与技术 本科",
        "work1": "阿里巴巴-淘天集团-SMEs 前端工程师",
        "introduction1": "我对音视频互动、多媒体技术、游戏开发感兴趣。大学期间，我掌握了一些软件开发技术，并且热衷于开发一些有趣的应用。工作后，主要负责多媒体素材处理，开发了一些音视频加工内核。除了业务和平台的前端开发工作，浏览器插件和服务端的一些开发也都长期在参与。",
        "introduction2": "在将来，我想去学习一些硬件开发技术，研发针对运动员的『智能可穿戴设备』。这些可穿戴设备能收集并分析团体运动中的数据，给出运动员更合理更奏效的战术策略、指导运动姿态、提高运动表现。",
        "project1name": "体感VR射击游戏",
        "project1introduction": "使用两部手机和自制的趁手武器，你也可以尝试体验VR第一人称射击游戏",
        "project2name": "GRE3000 CLI",
        "project2introduction": "上班摸鱼想背GRE单词？可以试试这个命令行工具。界面简洁隐蔽，比较适合摸鱼时候用😄还支持单词朗读",
        "project3name": "基于OCR的Chatbot",
        "project3introduction": "基于OCR快速标注页面窗口信息，实现几乎万能的chatbot部署。自定义回复脚本，快速打造你的gpt客服",
        "project4name": "DramaDirector模版视频引擎",
        "project4introduction": "基于Ffmpeg和Nodejs开发的模版视频合成sdk，支持视频/图片/lottie/字幕/音频、多轨道、转场、滤镜等效果",
        "project5name": "lottie动画转视频",
        "project5introduction": "在服务端通过puppeteer操作无头浏览器，基于webCodec和Ffmpeg实现lottie动画转视频，关于webCodec API的一个不错的学习和尝试",
        "project6name": "自定义塔防游戏",
        "project6introduction": "基于预设数据来驱动地图加载和怪兽波次，你还以自定义防御塔的样式和攻击属性。灵感来源于我很喜欢的一款塔防游戏《皇家守卫军》",
    },
    "en": {
        "name": "Jerry Ma",
        "nickname": "马聆风",
        "university1": "HUST - CS Bachelor's degree",
        "work1": "Alibaba Group SMEs - SDE",
        "introduction1": "I am interested in audio and video interaction, multimedia processing and game development. During university I learned some software development skills and was keen to develop some interesting applications. After work, I was mainly responsible for multimedia processing and developed some audio and video synthesis kernels. ",
        "introduction2": "In the future, I would like to learn some hardware development techniques and develop 「smart wearable devices」 for athletes. These wearable devices can collect and analyse data from team sports to provide athletes with more rational and effective tactical strategies, posture guidance and improved performance.",
        "project1name": "Motion Sensory VR Shooting Game",
        "project1introduction": "Using two mobile phones and homemade weapons, you can also try your hand at VR first-person shooters!",
        "project2name": "GRE3000 CLI",
        "project2introduction": "Wanna memorise GRE words at work? Try this CLI tool. The interface is simple and hidden, more suitable for working time use 😄 also support word read mod!",
        "project3name": "OCR Chatbot with GPT",
        "project3introduction": "The OCR Chatbot is an application for building a chatbot using pyautogui and CnOcr.It works by taking scheduled screenshots, managing message queues, and providing custom replies",
        "project4name": "DramaDirector SDK",
        "project4introduction": "A template video compositing SDK based on Ffmpeg and Nodejs, supporting video/image/lottie/subtitle/audio, multi-track, transitions, filters and other effects",
        "project5name": "lottie to video",
        "project5introduction": "Converting lottie animation to video through webCodec and Ffmpeg. A good project for learning and trying webCodec API!",
        "project6name": "Custom tower defence game",
        "project6introduction": "You can customise the map, monsters and defence properties with preset data. Inspired by one of my favourite tower defence games 「Kingdom Rush」",
    }
}
window.lang='en'